--this script initiates db for h2 db (used in test profile)
insert into user (account_status, email, first_name, last_name) values ('CONFIRMED', 'john@domain.com', 'John', 'Steward')
insert into user (account_status, email, first_name) values ('NEW', 'brian@domain.com', 'Brian')
insert into user (account_status, email, first_name, last_name) values ('REMOVED', 'removed@domain.com', 'Removed', 'User')
insert into blog_post values (null, 'post', 1)
insert into user (account_status, email, first_name, last_name) values ('CONFIRMED', 'liker@domain.com', 'Liker', 'Like')
